export const FETCH_CORONA_STATISTICS = 'FETCH_CORONA_STATISTICS';
export const SHOW_COUNTRY_STATISTICS = 'SHOW_COUNTRY_STATISTICS';
export const FETCH_MARKERS = 'FETCH_MARKERS';
export const MAP_STYLE= 'MAP_STYLE';
export const SET_ACTION = 'SET_ACTION';
export const MAP_STYLE_ACTION = 'MAP_STYLE_ACTION';
export const MAP_FLY_ACTION = 'MAP_FLY_ACTION';

export const BASE_URL = `http://192.168.1.15:9000`;
export const MAPBOX_ACCESS_TOKEN = `pk.eyJ1IjoidGh1YW5kb2FuMDkwMTA0IiwiYSI6ImNta2NycjR2dDA1M3UzZG9sOWF4cThnY3gifQ.8ZhrIFfnhHKiPYz0TdftIQ`;